Брать чаевые и общий счёт из GET-параметров
oshibka404/ohooligans pull request #14
Opened 2019-08-10 09:31 UTC by krigstask

2019-08-12 08:11 UTC, ElenaZimina commented on script.js
> +var prmstr = window.location.search.substr(1);
`var` используется в стандарте языка ES5. Поскольку скрипт написан с использованием стандарта ES6+, лучше заменить `var` на `const`.

2019-08-12 08:11 UTC, ElenaZimina commented on script.js
> +for ( var i = 0; i < prmarr.length; i++) {
В данной строке переменная `i` меняется, поэтому лучше заменить декларацию `var` на `let`. Также удали, пожалуйста, пробел после `(`.

2019-08-12 08:11 UTC, ElenaZimina commented on script.js
> +	if ( ! isNaN(tmparr[1]) ) {
Лишние пробелы вокруг `!`.

2019-08-12 08:11 UTC, ElenaZimina commented on script.js
> +var prmstr = window.location.search.substr(1);
Вообще, чтобы не наполнять глобальную область видимости новыми переменными (которые, к тому же, становятся свойствами объекта `window` 👻), что считается плохой практикой, стоит поместить весь новый код внутрь самовызываемой функции, которая начинается со строки 18. 
Смысл существования этой функции в том, чтобы все созданные в скрипте переменные остались локальными, а не стали глобальными.

2019-08-12 08:11 UTC, ElenaZimina commented on script.js
> +if ( params['total'] != null ) {
Лучше сравнивать с `undefined`. 
В спецификации это, конечно, не определено, но большинством разработчиков принято, что `undefined` - это что-то неизвестное, неопределенное. А `null` - то, что разработчик обнуляет намеренно.

2019-08-13 09:23 UTC, oshibka404 requested changes

2019-08-13 09:23 UTC, oshibka404 commented on script.js
> +	if (params['total'] != undefined) {
Для доступа к полям, имена которых известны, принято использовать dot notation вместо bracket notation. А `[]` — для случаев, когда имя поля хранится где-то в переменной.

По возможности всегда следует использовать `===` вместо `==` при сравнении, чтобы не дать приведению типов себя запутать.

И при проверке на `undefined` надёжнее использовать `typeof`, потому что ТЕОРЕТИЧЕСКИ где-то выше в коде может встретиться вполне валидная строчка `undefined = 'defined'`, хотя на практике вряд ли такое случится, конечно.

Короче, вот так:
```suggestion
	if (typeof params.total !== 'undefined') {
```

2019-08-13 09:23 UTC, oshibka404 commented on script.js
> +	if (params['tips'] != undefined) {
то же самое здесь:
```suggestion
	if (typeof params.tips !== 'undefined') {
```

2019-08-13 09:23 UTC, oshibka404 commented on script.js
> +		var tmparr = prmarr[i].split("=");
- `var` вообще [не стоит использовать](https://blog.usejournal.com/awesome-javascript-no-more-var-working-title-999428999994) в современном JS. Лучше использовать `let` если значение переменной меняется и `const` если не меняется
- Тут было бы удобно использовать [деструктурирующее присваивание](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) — а то `params[tmparr[0]] = tmparr[1]` выглядит непонятненько.
```suggestion
		const [paramName, paramValue] = prmarr[i].split("=");
```

2019-08-13 09:23 UTC, oshibka404 commented on script.js
> +	const prmstr = window.location.search.substr(1);
замечание по неймингу:
- в JS (вернее, во всех сколько-нибудь популярных стайлгайдах по JS) принято использовать `camelCase` в именах переменных.
- `prm` можно развернуть до полноценного `param`, a `str` — до `String`, а то мне понадобилась пара секунд чтобы это расшифровать имя (param string? primestar? poor master?).
```suggestion
	const paramString = window.location.search.substr(1);
```

2019-08-14 21:41 UTC, krigstask commented on script.js
> +	if (params['total'] != undefined) {
> Для доступа к полям, имена которых известны, принято использовать dot notation вместо bracket notation. А [] — для случаев, когда имя поля хранится где-то в переменной.

Я просто сначала не терял надежды сделать это циклом, но всё-таки у полей разные названия (-:Е

2019-08-23 09:01 UTC, oshibka404 requested changes
Ой, сорян, я тогда написал комментов и не засабмитил

2019-08-23 09:01 UTC, oshibka404 commented on script.js
> +		document.getElementById('people__total').innerText = params['total'];
ой, здесь не заметил
```suggestion
		document.getElementById('people__total').innerText = params.total;
```

2019-08-23 09:01 UTC, oshibka404 commented on script.js
> +		document.getElementById('tips').innerText = params['tips'];
```suggestion
		document.getElementById('tips').innerText = params.tips;
```
Когда пишешь через точку, то и подсветка синтаксиса лучше выглядит

2019-08-23 09:01 UTC, oshibka404 commented on script.js
> +	const paramArray = paramString.split("&");
ну и пусть останется только один вид кавычек
```suggestion
	const paramArray = paramString.split('&');
```

2019-08-23 09:01 UTC, oshibka404 commented on script.js
> +		const [paramName, paramValue] = paramArray[i].split("=");
```suggestion
		const [paramName, paramValue] = paramArray[i].split('=');
```

2019-08-23 09:01 UTC, oshibka404 commented on script.js
> +	const paramString = window.location.search.substr(1);
```suggestion
	const paramString = window.location.search.substr(1); // cut off `?` symbol
```
а то тоже не самая очевидная строчка

2019-08-23 09:31 UTC, oshibka404 approved these changes

2019-08-23 10:41 UTC, merged